/// Flutter icons Croosade
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Croosade
///      fonts:
///       - asset: fonts/Croosade.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
import 'package:flutter/widgets.dart';

class Croosade {
  Croosade._();

  static const _kFontFam = 'Croosade';
  static const _kFontPkg = null;

  static const IconData eye_1 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_3 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_outline = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData archer = IconData(0xe90d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_cluster = IconData(0xe911, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData axe = IconData(0xe917, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battered_axe = IconData(0xe91c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bone_knife = IconData(0xe939, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData broadsword = IconData(0xe946, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_of_circles = IconData(0xe965, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crossed_axes = IconData(0xe979, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crossed_pistols = IconData(0xe97b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crossed_sabres = IconData(0xe97c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crossed_swords = IconData(0xe97d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData daggers = IconData(0xe989, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData explosion = IconData(0xe9b1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flaming_claw = IconData(0xe9c9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plain_dagger = IconData(0xea65, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData revolver = IconData(0xea81, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skull = IconData(0xeaa1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spinning_sword = IconData(0xeab3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData splash = IconData(0xeab5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData supersonic_arrow = IconData(0xeac0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData target_arrows = IconData(0xeac3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_2 = IconData(0xf06e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xf3a8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
